<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'old_sound_rabbit_mq.payment_consumer' shared service.

include_once $this->targetDirs[3].'/src/Services/EventServiceude_once $this->targetDirs[3].'/src/Services/OrderService.php';
include_once $this->targetDirs[3].'/src/Services/TransactionService.php';
include_once $this->targetDirs[3].'/src/Services/EventService.php';
include_once $this->targetDirs[3].'/vendor/php-amqplib/rabbitmq-bundle/RabbitMq/ConsumerInterface.php';
include_once $this->targetDirs[3].'/src/Consumer/PaymentConsumer.php';
include_once $this->targetDirs[3].'/vendor/php-amqplib/rabbitmq-bundle/RabbitMq/BaseAmqp.php';
include_once $this->targetDirs[3].'/vendor/php-amqplib/rabbitmq-bundle/RabbitMq/DequeuerInterface.php';
include_once $this->targetDirs[3].'/vendor/php-amqplib/rabbitmq-bundle/RabbitMq/BaseConsumer.php';
include_once $this->targetDirs[3].'/vendor/php-amqplib/rabbitmq-bundle/RabbitMq/Consumer.php';

$this->services['old_sound_rabbit_mq.payment_consumer'] = $instance = new \OldSound\RabbitMqBundle\RabbitMq\Consumer(($this->services['old_sound_rabbit_mq.connection.default'] ?? $this->load('getOldSoundRabbitMq_Connection_DefaultService.php')));

$instance->setExchangeOptions(array('name' => 'billy.v1.payment', 'type' => 'direct', 'passive' => false, 'durable' => true, 'auto_delete' => false, 'internal' => false, 'nowait' => false, 'declare' => true, 'arguments' => NULL, 'ticket' => NULL));
$instance->setQueueOptions(array('name' => 'billy.v1.payment', 'passive' => false, 'durable' => true, 'exclusive' => false, 'auto_delete' => false, 'nowait' => false, 'declare' => true, 'arguments' => NULL, 'ticket' => NULL, 'routing_keys' => array()));
$instance->setCallback(array(0 => new \App\Consumer\PaymentConsumer(new \App\Services\EventService(), new \App\Services\OrderService(), new \App\Services\TransactionService(), new \App\Services\EventService()), 1 => 'execute'));
if ($this->has('event_dispatcher')) {
    $instance->setEventDispatcher(($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));
}

return $instance;
