<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Services\EventService' shared autowired service.

include_once $this->targetDirs[3].'/src/Services/EventService.php';

return $this->privates['App\Services\EventService'] = new \App\Services\EventService($this);
