<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIjdx3HF\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIjdx3HF/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIjdx3HF.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIjdx3HF\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerIjdx3HF\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Ijdx3HF',
    'container.build_id' => 'e7d10c1a',
    'container.build_time' => 1532571315,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerIjdx3HF');
